### ISSUE TITLE
When we have the official Telegram-iOS source code?

### ISSUE THREAD

**Issue by ZuzooVn** [telegram-messenger/Telegram-iOS#1]
Hi Guy

Telegram released the full official source code for Android for a long time ago and it has been updated day by day.

What's happen with Telegram-iOS?

Regards

**Comment by telegram-messenger** [comment]
Hello!

One day we will release it. Stay tuned!

Telegram Support.

**Comment by ZuzooVn** [comment]
Thank you

I'm waiting to your great job.

Regards
